spin_manifest_version = 2

[application]
authors = ["vamshireddy <vamshiproject02@gmail.com>"]
description = ""
name = "wordl-spin"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "wordl-spin"

[component.wordl-spin]
source = "target/wordl-spin.wasm"
exclude_files = ["**/node_modules"]
[component.wordl-spin.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]